apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: template-cicd
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: master
    - name: gitrepositoryurl
      description: The git repository url
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        generateName: cicd-run-
      spec:
        pipelineRef:
          name: build-git
        resources:
          - name: image
            resourceRef:
              name: image
          - name: source
            resourceSpec:
              type: git
              params:
                - name: revision
                  value: $(params.gitrevision)
                - name: url
                  value: $(params.gitrepositoryurl)
