apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: build
spec:
  resources:
    - name: source
      type: git
    - name: image
      type: image
  tasks:
    - name: task
      taskRef:
        name: build
      resources:
        inputs:
          - name: source
            resource: source
          - name: image
            resource: image
